### ISSUE TITLE
On startup: TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by sbromberger** [maprinz/numbers-on-a-pane#2]
Failed to activate package named 'numbers-on-a-pane' TypeError: Cannot read property 'apply' of undefined
  at Function.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:122:30)
  at Function.View.buildHtml (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:96:10)
  at NumbersOnAPaneView.View (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:121:33)
  at new NumbersOnAPaneView (/Users/seth/.atom/packages/numbers-on-a-pane/lib/numbers-on-a-pane-view.coffee:6:3)
  at Object.module.exports.activate (/Users/seth/.atom/packages/numbers-on-a-pane/lib/numbers-on-a-pane.coffee:7:31)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:227:27)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:213:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:159:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:207:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:404:21)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:393:14)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:379:19)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app/src/atom.js:584:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:59:25)

**Comment by Mokipay** [comment]
+1

**Comment by pirminis** [comment]
+1
