### ISSUE TITLE
Failed to load the numbers-on-a-pane package

### ISSUE THREAD

**Issue by insanetesterftw** [maprinz/numbers-on-a-pane#6]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [numbers-on-a-pane](https://github.com/maprinz/numbers-on-a-pane) package, v0.1.0
### Stack Trace

Failed to load the numbers-on-a-pane package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (C:\Users\Eckoff\.atom\packages\numbers-on-a-pane\lib\numbers-on-a-pane-view.coffee:1:1)
  at C:\Users\Eckoff\.atom\packages\numbers-on-a-pane\lib\numbers-on-a-pane-view.coffee:6:3
  at Object.<anonymous> (C:\Users\Eckoff\.atom\packages\numbers-on-a-pane\lib\numbers-on-a-pane-view.coffee:38:5)
  at Object.<anonymous> (C:\Users\Eckoff\.atom\packages\numbers-on-a-pane\lib\numbers-on-a-pane-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\Eckoff\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Eckoff\.atom\packages\numbers-on-a-pane\lib\numbers-on-a-pane.coffee:1:22)
  at Object.<anonymous> (C:\Users\Eckoff\.atom\packages\numbers-on-a-pane\lib\numbers-on-a-pane.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\Eckoff\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\Eckoff\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package.js:759:34)
  at C:\Users\Eckoff\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package.js:190:28
  at Package.module.exports.Package.measure (C:\Users\Eckoff\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package.js:167:15)
  at Package.module.exports.Package.load (C:\Users\Eckoff\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Eckoff\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package-manager.js:405:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Eckoff\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package-manager.js:485:30)
  at C:\Users\Eckoff\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\settings-view\lib\package-manager.js:370:29
  at exit (C:\Users\Eckoff\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\settings-view\lib\package-manager.js:59:16)
  at triggerExitCallback (C:\Users\Eckoff\AppData\Local\atom\app-1.0.7\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\Eckoff\AppData\Local\atom\app-1.0.7\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
markdown-folder, v0.1.0
numbers-on-a-pane, v0.1.0
tabular, v0.1.0

# Dev
No dev packages
```

**Comment by zedtux** [comment]
Same issue here on OSX 10.11.6
